package com.vxianjin.gringotts.pay.model;

import java.util.Date;

public class OrderChangeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.user_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.borrow_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.operate_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String operateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.operate_type
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.action
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.before_status
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String beforeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.after_status
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String afterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.is_delete
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.create_time
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.update_time
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_log.remark
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.id
     *
     * @return the value of order_change_log.id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.id
     *
     * @param id the value for order_change_log.id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.user_id
     *
     * @return the value of order_change_log.user_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.user_id
     *
     * @param userId the value for order_change_log.user_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.borrow_id
     *
     * @return the value of order_change_log.borrow_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.borrow_id
     *
     * @param borrowId the value for order_change_log.borrow_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId == null ? null : borrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.operate_id
     *
     * @return the value of order_change_log.operate_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.operate_id
     *
     * @param operateId the value for order_change_log.operate_id
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setOperateId(String operateId) {
        this.operateId = operateId == null ? null : operateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.operate_type
     *
     * @return the value of order_change_log.operate_type
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.operate_type
     *
     * @param operateType the value for order_change_log.operate_type
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.action
     *
     * @return the value of order_change_log.action
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.action
     *
     * @param action the value for order_change_log.action
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.before_status
     *
     * @return the value of order_change_log.before_status
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getBeforeStatus() {
        return beforeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.before_status
     *
     * @param beforeStatus the value for order_change_log.before_status
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setBeforeStatus(String beforeStatus) {
        this.beforeStatus = beforeStatus == null ? null : beforeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.after_status
     *
     * @return the value of order_change_log.after_status
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getAfterStatus() {
        return afterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.after_status
     *
     * @param afterStatus the value for order_change_log.after_status
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setAfterStatus(String afterStatus) {
        this.afterStatus = afterStatus == null ? null : afterStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.is_delete
     *
     * @return the value of order_change_log.is_delete
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.is_delete
     *
     * @param isDelete the value for order_change_log.is_delete
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.create_time
     *
     * @return the value of order_change_log.create_time
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.create_time
     *
     * @param createTime the value for order_change_log.create_time
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.update_time
     *
     * @return the value of order_change_log.update_time
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.update_time
     *
     * @param updateTime the value for order_change_log.update_time
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_log.remark
     *
     * @return the value of order_change_log.remark
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_log.remark
     *
     * @param remark the value for order_change_log.remark
     *
     * @mbg.generated Tue Aug 21 15:57:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}