package com.vxianjin.gringotts.pay.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserQuotaSnapshot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.user_id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.borrow_product_id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private Integer borrowProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.deal_flag
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private String dealFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.create_time
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.update_time
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrowquota_snapshot.remark
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    private String remark;



    private Integer borrowDay;


    private BigDecimal userAmountLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.id
     *
     * @return the value of user_borrowquota_snapshot.id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.id
     *
     * @param id the value for user_borrowquota_snapshot.id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.user_id
     *
     * @return the value of user_borrowquota_snapshot.user_id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.user_id
     *
     * @param userId the value for user_borrowquota_snapshot.user_id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.borrow_product_id
     *
     * @return the value of user_borrowquota_snapshot.borrow_product_id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public Integer getBorrowProductId() {
        return borrowProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.borrow_product_id
     *
     * @param borrowProductId the value for user_borrowquota_snapshot.borrow_product_id
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setBorrowProductId(Integer borrowProductId) {
        this.borrowProductId = borrowProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.deal_flag
     *
     * @return the value of user_borrowquota_snapshot.deal_flag
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public String getDealFlag() {
        return dealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.deal_flag
     *
     * @param dealFlag the value for user_borrowquota_snapshot.deal_flag
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setDealFlag(String dealFlag) {
        this.dealFlag = dealFlag == null ? null : dealFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.create_time
     *
     * @return the value of user_borrowquota_snapshot.create_time
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.create_time
     *
     * @param createTime the value for user_borrowquota_snapshot.create_time
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.update_time
     *
     * @return the value of user_borrowquota_snapshot.update_time
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.update_time
     *
     * @param updateTime the value for user_borrowquota_snapshot.update_time
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrowquota_snapshot.remark
     *
     * @return the value of user_borrowquota_snapshot.remark
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrowquota_snapshot.remark
     *
     * @param remark the value for user_borrowquota_snapshot.remark
     *
     * @mbggenerated Tue Sep 11 10:29:05 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }


    public Integer getBorrowDay() {
        return borrowDay;
    }

    public void setBorrowDay(Integer borrowDay) {
        this.borrowDay = borrowDay;
    }

    public BigDecimal getUserAmountLimit() {
        return userAmountLimit;
    }

    public void setUserAmountLimit(BigDecimal userAmountLimit) {
        this.userAmountLimit = userAmountLimit;
    }
}