package com.vxianjin.gringotts.pay.model;

import java.io.Serializable;
import java.util.Date;

public class UserQuotaApplyLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota_apply_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota_apply_log.user_Id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota_apply_log.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota_apply_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota_apply_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota_apply_log.error_Num
     *
     * @mbggenerated
     */
    private Integer errorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_quota_apply_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota_apply_log.id
     *
     * @return the value of user_quota_apply_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota_apply_log.id
     *
     * @param id the value for user_quota_apply_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota_apply_log.user_Id
     *
     * @return the value of user_quota_apply_log.user_Id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota_apply_log.user_Id
     *
     * @param userId the value for user_quota_apply_log.user_Id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota_apply_log.status
     *
     * @return the value of user_quota_apply_log.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota_apply_log.status
     *
     * @param status the value for user_quota_apply_log.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota_apply_log.create_time
     *
     * @return the value of user_quota_apply_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota_apply_log.create_time
     *
     * @param createTime the value for user_quota_apply_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota_apply_log.update_time
     *
     * @return the value of user_quota_apply_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota_apply_log.update_time
     *
     * @param updateTime the value for user_quota_apply_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota_apply_log.error_Num
     *
     * @return the value of user_quota_apply_log.error_Num
     *
     * @mbggenerated
     */
    public Integer getErrorNum() {
        return errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota_apply_log.error_Num
     *
     * @param errorNum the value for user_quota_apply_log.error_Num
     *
     * @mbggenerated
     */
    public void setErrorNum(Integer errorNum) {
        this.errorNum = errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota_apply_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserQuotaApplyLog other = (UserQuotaApplyLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getErrorNum() == null ? other.getErrorNum() == null : this.getErrorNum().equals(other.getErrorNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota_apply_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getErrorNum() == null) ? 0 : getErrorNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota_apply_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", errorNum=").append(errorNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public UserQuotaApplyLog(Integer userId, Date createTime) {
        this.userId = userId;
        this.createTime = createTime;
    }

    public UserQuotaApplyLog(Integer userId, String status) {
        this.userId = userId;
        this.status = status;
    }

    public UserQuotaApplyLog() {
    }

    public UserQuotaApplyLog(Integer userId) {
        this.userId = userId;
        this.createTime = new Date();
    }
}