package com.vxianjin.gringotts.pay.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserCreditquotaLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.id
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.user_id
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.quota_type
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private String quotaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.action
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.before_quota
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private BigDecimal beforeQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.after_quota
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private BigDecimal afterQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.is_delete
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.create_time
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.update_time
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_creditquota_log.remark
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    private String remark;


    private String projectName;


    private String dataChangeTime;


    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getDataChangeTime() {
        return dataChangeTime;
    }

    public void setDataChangeTime(String dataChangeTime) {
        this.dataChangeTime = dataChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.id
     *
     * @return the value of user_creditquota_log.id
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.id
     *
     * @param id the value for user_creditquota_log.id
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.user_id
     *
     * @return the value of user_creditquota_log.user_id
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.user_id
     *
     * @param userId the value for user_creditquota_log.user_id
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.quota_type
     *
     * @return the value of user_creditquota_log.quota_type
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public String getQuotaType() {
        return quotaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.quota_type
     *
     * @param quotaType the value for user_creditquota_log.quota_type
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setQuotaType(String quotaType) {
        this.quotaType = quotaType == null ? null : quotaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.action
     *
     * @return the value of user_creditquota_log.action
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.action
     *
     * @param action the value for user_creditquota_log.action
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.before_quota
     *
     * @return the value of user_creditquota_log.before_quota
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public BigDecimal getBeforeQuota() {
        return beforeQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.before_quota
     *
     * @param beforeQuota the value for user_creditquota_log.before_quota
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setBeforeQuota(BigDecimal beforeQuota) {
        this.beforeQuota = beforeQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.after_quota
     *
     * @return the value of user_creditquota_log.after_quota
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public BigDecimal getAfterQuota() {
        return afterQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.after_quota
     *
     * @param afterQuota the value for user_creditquota_log.after_quota
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setAfterQuota(BigDecimal afterQuota) {
        this.afterQuota = afterQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.is_delete
     *
     * @return the value of user_creditquota_log.is_delete
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.is_delete
     *
     * @param isDelete the value for user_creditquota_log.is_delete
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.create_time
     *
     * @return the value of user_creditquota_log.create_time
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.create_time
     *
     * @param createTime the value for user_creditquota_log.create_time
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.update_time
     *
     * @return the value of user_creditquota_log.update_time
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.update_time
     *
     * @param updateTime the value for user_creditquota_log.update_time
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_creditquota_log.remark
     *
     * @return the value of user_creditquota_log.remark
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_creditquota_log.remark
     *
     * @param remark the value for user_creditquota_log.remark
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}