package com.vxianjin.gringotts.pay.dao;

import com.vxianjin.gringotts.pay.model.MqInfo;

import java.util.List;

public interface IMqInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_info
     *
     * @mbggenerated
     */
    int insert(MqInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_info
     *
     * @mbggenerated
     */
    int insertSelective(MqInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_info
     *
     * @mbggenerated
     */
    MqInfo selectByPrimaryKey(String mqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqInfo record);

    int updateToSuccess(String mqKey);

    int updateToError(String mqKey);

    List<MqInfo> queryUnSuccessMqInfo();

    int updateMqSendTime(String mqKey);
}