package com.vxianjin.gringotts.pay.dao;

import com.vxianjin.gringotts.pay.model.OrderChangeLog;

public interface OrderChangeLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_log
     *
     * @mbg.generated Tue Aug 21 11:42:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_log
     *
     * @mbg.generated Tue Aug 21 11:42:00 CST 2018
     */
    int insert(OrderChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_log
     *
     * @mbg.generated Tue Aug 21 11:42:00 CST 2018
     */
    int insertSelective(OrderChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_log
     *
     * @mbg.generated Tue Aug 21 11:42:00 CST 2018
     */
    OrderChangeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_log
     *
     * @mbg.generated Tue Aug 21 11:42:00 CST 2018
     */
    int updateByPrimaryKeySelective(OrderChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_log
     *
     * @mbg.generated Tue Aug 21 11:42:00 CST 2018
     */
    int updateByPrimaryKey(OrderChangeLog record);


    int addNewOrderChangeLog(OrderChangeLog record);
}