package com.vxianjin.gringotts.pay.dao;

import com.vxianjin.gringotts.pay.model.UserCreditquotaLog;

public interface UserCreditquotaLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_creditquota_log
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_creditquota_log
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    int insert(UserCreditquotaLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_creditquota_log
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    int insertSelective(UserCreditquotaLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_creditquota_log
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    UserCreditquotaLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_creditquota_log
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    int updateByPrimaryKeySelective(UserCreditquotaLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_creditquota_log
     *
     * @mbggenerated Tue Sep 11 10:29:55 CST 2018
     */
    int updateByPrimaryKey(UserCreditquotaLog record);

    /**
     * 新增用户额度变化日志
     * @param record
     * @return
     */
    int addNewUserQuotaLog(UserCreditquotaLog record);
}