package com.vxianjin.gringotts.web.pojo;

import java.io.Serializable;
import java.util.Date;

public class AppUpdateConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.app_version
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.app_type
     *
     * @mbggenerated
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.app_url
     *
     * @mbggenerated
     */
    private String appUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.force_type
     *
     * @mbggenerated
     */
    private Integer forceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.deal_flag
     *
     * @mbggenerated
     */
    private String dealFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_update_config.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.id
     *
     * @return the value of app_update_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.id
     *
     * @param id the value for app_update_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.app_version
     *
     * @return the value of app_update_config.app_version
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.app_version
     *
     * @param appVersion the value for app_update_config.app_version
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.app_type
     *
     * @return the value of app_update_config.app_type
     *
     * @mbggenerated
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.app_type
     *
     * @param appType the value for app_update_config.app_type
     *
     * @mbggenerated
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.content
     *
     * @return the value of app_update_config.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.content
     *
     * @param content the value for app_update_config.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.app_url
     *
     * @return the value of app_update_config.app_url
     *
     * @mbggenerated
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.app_url
     *
     * @param appUrl the value for app_update_config.app_url
     *
     * @mbggenerated
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl == null ? null : appUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.force_type
     *
     * @return the value of app_update_config.force_type
     *
     * @mbggenerated
     */
    public Integer getForceType() {
        return forceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.force_type
     *
     * @param forceType the value for app_update_config.force_type
     *
     * @mbggenerated
     */
    public void setForceType(Integer forceType) {
        this.forceType = forceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.deal_flag
     *
     * @return the value of app_update_config.deal_flag
     *
     * @mbggenerated
     */
    public String getDealFlag() {
        return dealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.deal_flag
     *
     * @param dealFlag the value for app_update_config.deal_flag
     *
     * @mbggenerated
     */
    public void setDealFlag(String dealFlag) {
        this.dealFlag = dealFlag == null ? null : dealFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.create_time
     *
     * @return the value of app_update_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.create_time
     *
     * @param createTime the value for app_update_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.update_time
     *
     * @return the value of app_update_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.update_time
     *
     * @param updateTime the value for app_update_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_update_config.remark
     *
     * @return the value of app_update_config.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_update_config.remark
     *
     * @param remark the value for app_update_config.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppUpdateConfig other = (AppUpdateConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppVersion() == null ? other.getAppVersion() == null : this.getAppVersion().equals(other.getAppVersion()))
            && (this.getAppType() == null ? other.getAppType() == null : this.getAppType().equals(other.getAppType()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getAppUrl() == null ? other.getAppUrl() == null : this.getAppUrl().equals(other.getAppUrl()))
            && (this.getForceType() == null ? other.getForceType() == null : this.getForceType().equals(other.getForceType()))
            && (this.getDealFlag() == null ? other.getDealFlag() == null : this.getDealFlag().equals(other.getDealFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppVersion() == null) ? 0 : getAppVersion().hashCode());
        result = prime * result + ((getAppType() == null) ? 0 : getAppType().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getAppUrl() == null) ? 0 : getAppUrl().hashCode());
        result = prime * result + ((getForceType() == null) ? 0 : getForceType().hashCode());
        result = prime * result + ((getDealFlag() == null) ? 0 : getDealFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appVersion=").append(appVersion);
        sb.append(", appType=").append(appType);
        sb.append(", content=").append(content);
        sb.append(", appUrl=").append(appUrl);
        sb.append(", forceType=").append(forceType);
        sb.append(", dealFlag=").append(dealFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}