package com.vxianjin.gringotts.web.dao;

import com.vxianjin.gringotts.web.pojo.AppUpdateConfig;

import java.util.List;

public interface IAppUpdateConfigDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    int insert(AppUpdateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    int insertSelective(AppUpdateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    AppUpdateConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppUpdateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_update_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppUpdateConfig record);

    /**
     * 查询所有版本列表
     * @return
     */
    List<AppUpdateConfig> findList(String appType);
}