package com.vxianjin.gringotts.web.dao;

import com.vxianjin.gringotts.web.pojo.UserClientInfo;

public interface IUserClientInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_client_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_client_info
     *
     * @mbggenerated
     */
    int insert(UserClientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_client_info
     *
     * @mbggenerated
     */
    int insertSelective(UserClientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_client_info
     *
     * @mbggenerated
     */
    UserClientInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_client_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserClientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_client_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserClientInfo record);

    int updateByUserId(Integer userId,String clientId);

    String queryClientIdByUserId(int userId);
}